### ISSUE TITLE
user-can-see-their-car

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create HTML Skeleton
- [x] Add a section for the race track
- [x] Add a div element
  - [x] Inside of this div, add an img element with the src attribute set to the image of the f1 race car
- [x] Update styling for the vehicle
- [x] Double check styling and remove what is not necessary
