### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/driving-game#2]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Set the div containing the img child with absolute positioning
- [x] Query the DOM for the div element containing the f1 racer image
- [x] Create a Data Model to log the direction, x, and y coordinates of the f1 racer
- [x] Define a function that will:
  - [x] Assign the offsetLeft positioning to a variable
  - [x] Update the left style property with an expression
  - [x] Update the object models location x property value to the left style property value
- [x] The vehicle will move right every 16 milliseconds when the user hits their space bar
  - [x] Ensure the vehicle does not increase in speed when the user presses their space bar
- [x] Test the feature for bugs, fix them where necessary

**Comment by OSAdams** [comment]
![driving-game-start-car](https://user-images.githubusercontent.com/76730244/169935673-3e45c410-629c-4038-8dbc-14ea903376f4.gif)
