### ISSUE TITLE
user-can-steer-their-car

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/driving-game#3]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Update the startF1Racer function to have:
  - [x] The image of the f1 racer offsetTop value assigned to a let variable topPos
  - [x] The image of the f1 racer offsetLeft value assigned to a let variable leftPos
- [x] When f1Data.direction value is either 'north' or 'south', execute:
  - [x] for 'north', subtract and re-assign the value of topPos by 3
  - [x] for 'south, add and re-assign the value of topPos by 3
  - [x] update the value of f1Racer.style.left to the value of leftPost + 'px'
  - [x] update the value of f1Data.location.y to the value of topPos
- [x] When f1Data.direction value is either 'east' or 'west', execute:
  - [x] for 'west', subtract and re-assign the value of leftPos by 3
  - [x] for 'east, add and re-assign the value of leftPos by 3
  - [x] update the value of f1Racer.style.top to the value of leftPost + 'px'
  - [x] update the value of f1Data.location.x to the value of leftPos
- [x] Test functionality and fix all bugs
