### ISSUE TITLE
user-can-stop-their-car

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] if (intervalID !== null) 
  - [x] remove setInterval(intervalID, 16)
  - [x] add clearInterval(intervalID)
  - [x] assign null value to intervalID
