### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/driving-game#5]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] To the window event listener, add conditionals for which key is pressed
  - [x] Add one for W or Up Arrow
  - [x] Add one for A or Left Arrow
  - [x] Add one for S or Down Arrow
  - [x] Add one for D or Right Arrow
 - [x] Depending on which key is pressed, rotate the image using translate
   - [x] W or Up Arrow 
     - [x] rotate the image to -90 deg
     - [x] set the value of direction to 'north'
   - [x] A or Left Arrow
     - [x] rotate the image to -180 deg
     - [x] set the value of direction to 'west' 
   - [x]  S or Down Arrow
     - [x] rotate the image to 90 deg
     - [x] set the value of direction to 'south'
   - [x] D or Right Arrow
     - [x] rotate the image to 0 deg
     - [x] set the value of direction to 'east'
- [x] Test functionality and fix all bugs
